# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jstcpp <- function(dfm, sentiWords, sentiCategory, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_) {
    .Call('_sentitopics_jstcpp', PACKAGE = 'sentitopics', dfm, sentiWords, sentiCategory, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_)
}

jstcppreversed <- function(dfm, sentiWords, sentiCategory, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_) {
    .Call('_sentitopics_jstcppreversed', PACKAGE = 'sentitopics', dfm, sentiWords, sentiCategory, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_)
}

topNwordSeeds <- function(wordParameters, N) {
    .Call('_sentitopics_topNwordSeeds', PACKAGE = 'sentitopics', wordParameters, N)
}

